In [1]:
import numpy as np 
import scipy 
import scipy.linalg
np.set_printoptions(precision=2, suppress=True)

###  1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [2]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [3]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [4]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [5]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [6]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1.  0. -0.]
 [ 0. -0.  0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [7]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [8]:
# Убедимся, что она действительно ортогональна
print(np.dot(V.T, V))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


#### Евклидова норма равна 

$$\left \| A \right \|_{E}=\mu_{1}=8.82.$$


#### В случае, когда известно сингулярное разложение матрицы, ее норма Фробениуса вычисляется как

$$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}.$$

In [11]:
A_F = np.sqrt(8.82**2+6.14**2+2.53**2)
print(f'Норма Фробениуса A_F:\n{A_F}')

Норма Фробениуса A_F:
11.04051176350082


#### Найдем матрицы D и V из определения

In [21]:
u, v = np.linalg.eig(np.dot(A, A.T))
print(f'Матрица A*A_T:\n{np.dot(A, A.T)}')
print(f'Собственные значения A*A_T (квадраты сингулярных чисел):\n{u}')
print(f'Собственные векторы A*A_T (это и есть матрица U):\n{v}')

Матрица A*A_T:
[[  5   0  -5  13   2]
 [  0  25  10  25   0]
 [ -5  10  29 -11  -4]
 [ 13  25 -11  62   6]
 [  2   0  -4   6   1]]
Собственные значения A*A_T (квадраты сингулярных чисел):
[77.88 37.71  6.41 -0.    0.  ]
Собственные векторы A*A_T (это и есть матрица U):
[[-0.17  0.16  0.53  0.81 -0.01]
 [-0.39 -0.53 -0.61  0.4  -0.12]
 [ 0.14 -0.82  0.52 -0.16 -0.04]
 [-0.89  0.06  0.25 -0.34  0.14]
 [-0.08  0.11  0.08 -0.23 -0.98]]


In [24]:
# Убедимся, что она действительно ортогональна
print(np.dot(v.T, v))

[[ 1. -0. -0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]


In [23]:
u, v = np.linalg.eig(np.dot(A.T, A))
print(f'Матрица A_T*A:\n{np.dot(A.T, A)}')
print(f'Собственные значения A_T*A (квадраты сингулярных чисел):\n{u}')
print(f'Собственные векторы A_T*A (это и есть матрица V):\n{v}')

Матрица A_T*A:
[[11 -4 11]
 [-4 57 22]
 [11 22 54]]
Собственные значения A_T*A (квадраты сингулярных чисел):
[ 6.41 37.71 77.88]
Собственные векторы A_T*A (это и есть матрица V):
[[-0.93 -0.37  0.07]
 [-0.21  0.67  0.72]
 [ 0.31 -0.65  0.69]]


In [25]:
# Убедимся, что она действительно ортогональна
print(np.dot(v.T, v))

[[ 1. -0. -0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]
